### ISSUE TITLE
destination disk is too small

### ISSUE THREAD

**Issue by ohhmm** [stevenshiau/clonezilla#1]
It could be most appropriate to use partition data sizes to make the decision id disk really too small. And make proportional size increase/decrease automatically.

**Comment by bordenc** [comment]
Being able to clone to a smaller disk is becoming pretty important as we move to SSDs (especially on laptops). I had 5 of the worst days of my life trying to switch a 1 TB laptop drive to a 0.5 TB M.2 because Micro$oft's Winblows 11 has made user files and settings transfers next to impossible. The madness finally stopped when Acronis True Image from WD miraculously did a perfect clone and resize, but I can't rely that next time the software will (a) work; and (b) be free.

Yes, I know there is a workaround to use a gparted shrink first, but we also know that humans are far more error-prone than computers, so automating this as much as possible would be very helpful.

**Comment by stevenshiau** [comment]
Thanks for your feedback. Maybe someday this will be implemented with a nicer method.
So far the workaround using GParted to shrink is the best for Clonezilla with the file system engine Partclone.

**Comment by bordenc** [comment]
If I knew the first thing about low-level partition management, I'd offer to help. Is there anything non-technical people can do to help?

**Comment by stevenshiau** [comment]
Well, this is not really an easy job... Basically we try to make Clonezilla as a massive deployment tool + a backup/recovery tool. To combine these two goals, some parts might have to be sacrificed...

**Comment by bordenc** [comment]
> Well, this is not really an easy job... Basically we try to make Clonezilla as a massive deployment tool + a backup/recovery tool. To combine these two goals, some parts might have to be sacrificed...

If I understand, correctly, it's a major bottom-up redesign and rewrite. So probably a better job for a fork than a wishlist?

**Comment by stevenshiau** [comment]
Well, you can say that.
Actually fsarchiver might work for you, just you have to do more things if what you want is not just a file system cloning:
https://www.fsarchiver.org/

Steven

**Comment by bordenc** [comment]
Suggest close wontfix and redirect future enquires to this thread, since it doesn't seem feasible with current resources to implement.

**Comment by stevenshiau** [comment]
Sure.
