### ISSUE TITLE
ocs-onthefly not supporting nvme?

### ISSUE THREAD

**Issue by hahaxd35** [stevenshiau/clonezilla#61]
Hi,

yesterday i tried to clone a nvme drive via network.

The command exit right after: nc 192.168.0.1 9003 
connection refused

I had trouble to find the problem but i think the problem was that ocs-onthefly checks the device name?

ocs-onthefly only supporting "sdX" and "vdX" as devices names/arguments?

it sayes "use sda or vda" or similar  

makes this sense?

**Comment by stevenshiau** [comment]
How did you run that? Please describe the Clonezilla live version, and the steps how you run in detail so that we can try to reproduce this issue.
In addition, please take a photo about the error messages on the screen then post it.

Steven

**Comment by hahaxd35** [comment]
I download yesterday the current clonzilla live iso.
DD it to two usb sticks. 

Booted each into clonezilla.

source PC i selected "remote-source" and dest PC i selected "remote-dest"

i have configured cloning as recommended and then conneted the dest maschine with "ocs-onthefly -s IP-from-source -t nvme0n1"
(with /dev/nvme0n1 too)

This just "finished" with last line "connection refused" and showed the help
nc IP-from-source 9003
i have check the errors by using screen.  Sadly i cannot reproduce know.


after some failed cloning, i tried testing 
"nc 192.168.123.245 9003"

output:
source_type=disk

too lock if there some connection issues but there does not. 

Maybe i can send tomorrow a screenshot

**Comment by stevenshiau** [comment]
It might due to the firewall that blocks the network port 9003. Hence please make sure your firewall does not block it.

Steven

**Comment by hahaxd35** [comment]
i did run this command  to check if there was problem and i got a output....

looks like the firewall....
i have tried to reproduce this failure with only one PC and a fake source-pc (using ncat)
This is one error i got like:

![IMG_20211109_151531](https://user-images.githubusercontent.com/48324739/140942859-f4a3ff74-a5cd-46c7-94f4-e369e167e117.jpg)

often there was a help displayed

**Comment by hahaxd35** [comment]
is this the right repository?

**Comment by stevenshiau** [comment]
So which version of Clonezilla live did you use? I asked before and you did not reply. We'd like to try the same version you have and to see if this issue is reproducible here.

Steven

**Comment by stevenshiau** [comment]
I did a test using Clonezilla live 2.7.3-19 amd64 release, and I can not reproduce this issue.

Attached you can find two files, sda-src.txt is the output on the screen of source machine, and nvme-dest.txt is the output on the screen of destination machine.

[sda-src.txt](https://github.com/stevenshiau/clonezilla/files/7539095/sda-src.txt)
[nvme-dest.txt](https://github.com/stevenshiau/clonezilla/files/7539097/nvme-dest.txt)

Steven

**Comment by hahaxd35** [comment]
> i have test this again:
> 
> source-pc has a sda device so it worked know....

bug was about two nvme devices.

Is my english soo bad?

**Comment by hahaxd35** [comment]
i just had the feeling that a script or somethings else checks the device name contains "/dev/sd". when source pc want to clone nvme, this scipts shows help page because of wrong "argument"

**Comment by stevenshiau** [comment]
I tested what I have here, so it was sda to nvme. This test case is more complicated than two nvme devices. Most of the time the different device name smight cause issues. 
Anyhow, I did a test again about nvme to nvme, and it worked without any issue. 
You can see from the log file I provided in the previous post:
### 
This is for target machine
Running: nc  192.168.120.1 9003 > /tmp/ocs_onthefly_tgt.claUGq/target_type.ocs_onthefly
Running: nc  192.168.120.1 9009 > /tmp/ocs_onthefly_tgt.claUGq/d2d-pseudo.tgz
*****************************************************.
*****************************************************.
Cloning the source device to /dev/nvme0n1. Running:
LC_ALL=C ocs-sr --ocsroot /tmp/ocs_onthefly_tgt.claUGq -l en_US.UTF-8 --batch -j2 -scr -p true --data-port 9015 -g auto -e1 auto -e2 -r -j2 -fsck-y -s 192.168.120.1 nd2d_restoredisk d2d-pseudo nvme0n1
Setting the TERM as screen
Starting /usr/sbin/ocs-sr at 2021-11-15 13:59:17 UTC...
### 

While yours stopped at "nc" with error messages "connection refused". That's the key issue. Clonezilla can not receive the tarball containing the required info from source machine. That's why it stopped there.

Steven

**Comment by hahaxd35** [comment]
OK strange....
I just use the GUI and it didn't worked...

its was not a firewall issue, because i'm administrator and we dont block local request or Ports 

when i got both PC back i will test it again.

when its not working i will use:

dd if=/dev/vvmen0p1 | ssh root@IP | dd of=/dev/nvmen0p1
