### ISSUE TITLE
Question about the "brltty" package and output to more than one console

### ISSUE THREAD

**Issue by Shivansps** [stevenshiau/clonezilla#74]
Hi,
im working on a little project using an microcontroller like an arduino to add a text output/progress indicator, and maybe even sending comands like, to clone a specific image, etc. To a headless clonezilla pc. I plan to make it public once its done.

The first thing that gets in the way is the brltty package, Arduino and devices like an NodeMCU ESP8266 usually comes with a CH340/CH341 built-in meaning i can just connect to the USB and there is going to be a console avalible at ttyUSB0 to point the kernel and clonezilla to, BUT the brltty package thinks the ch340/341 us a braille device and takes control over them. So in order for this to work ill need to provide instruccions on how to remove this package from the .squash rootfs. I dont think there is going to be any problem, but there is a reason for this package to be in?
Im going to also have an option on using a motherboard rs232 as option, the works around this issue, but requieres extra hardware, and a motherboard with a rs232 header.

The second question is that i dont really want to remove the possibility of using a keyboard and monitor, the linux kernel already provides an option to output to multiples consolesby doing;

console=ttyS0,9600n81 console=tty1

But i cant do this
ocs_live_run_tty=/dev/ttyS0  ocs_live_run_tty=tty1

as it only outputs to the last one. I also tried tricks to clone outputs, like this ocs_pre_run="script -f /dev/ttyS0" so tty1 would be copied to ttyS0, but this seems to interrupt the clonezilla script so cloning never starts if you also passed ocs_live_run="" to clone in unattended mode.

**Comment by stevenshiau** [comment]
As for your first question, you can refer to this:
https://drbl.org/fine-print.php?path=./faq/2_System/81_add_prog_in_filesystem-squashfs.faq#81_add_prog_in_filesystem-squashfs.faq

As for 2nd question, you can just ignore ocs_live_run_tty. It's used to start the Clonezilla wizard TUI.
Since it's headless, you can just run:
sudo clonezilla
to start the TUI after you enter command line prompt. No need to care about the ocs_live_run_tty parameter.

Steven
